spring:
  application:
    name: reactive

  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost/postgres
    user: postgres
    password: postgres

deepl:
  apiBaseUrl: https://api.deepl.com
  apiKey: xxxxxxxxxxxxxxxxx