spring:
  application:
    name: reactive

  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost/postgres
    user: postgres
    password: postgres

deepl:
  apiBaseUrl: https://api-free.deepl.com
  apiKey: ef0c5916-93ca-4566-b178-218be5ad0882:fx